version: '3.8'
services: 
  hotelapi:
    image: hotelapi
    build:
      context: .
      dockerfile: BackendAPI/Dockerfile
    ports:
      - "5100:80"
      - "5101:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https-certs/your_cert.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "test"
    volumes:
      - certs:/https-certs:ro
    secrets:
      - cert-password

  hotelwebapp:
    image: hotelwebapp
    build:
      context: .
      dockerfile: HotelsWebApp/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Release"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https-certs/your_cert.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "test"
      cert-password: /run/secrets/cert-password
    volumes:
      - certs:/https-certs:ro
    secrets:
      - cert-password

volumes:
  certs:
    external: true

secrets:
  cert-password:
    external: true
