version: '3.8'
services: 
  hotelapi:
    image: hotelapi
    build:
      context: .
      dockerfile: BackendAPI/Dockerfile
    ports:
      - "5100:80"
      - "5101:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5101"
      ASPNETCORE_ENVIRONMENT: "Development"
      CERT_PATH: "/https-certs/your_cert.pfx"
      CERT_PASSWORD: /run/secrets/CertPassword
    volumes:
      - certs:/https-certs:ro
    secrets:
      - CertPassword

  hotelwebapp:
    image: hotelwebapp
    build:
      context: .
      dockerfile: HotelsWebApp/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Release"
      CERT_PATH: "/https-certs/your_cert.pfx"
      CERT_PASSWORD: /run/secrets/CertPassword
    volumes:
      - certs:/https-certs:ro
    secrets:
      - CertPassword

volumes:
  certs:
    external: true

secrets:
  CertPassword:
    external: true
