version: '3.8'
services: 
  hotelapi:
    image: hotelapi
    build:
      context: .
      dockerfile: BackendAPI/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "test"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "/run/secrets/cert-password"
    volumes:
      - ./certs:/https-certs:ro
    secrets:
      - cert-password

  hotelwebapp:
    image: hotelwebapp
    build:
      context: .
      dockerfile: HotelsWebApp/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Release"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "test"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "/run/secrets/cert-password"
    volumes:
      - ./certs:/https-certs:ro
    secrets:
      - cert-password

secrets:
  cert-password:
    external: true
