version: '3'
services: 
  testapi:
    image: testapi
    build:
      dockerfile: BackendAPI/Dockerfile
    ports:
    - "8080:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"